// stdout: a standard input stream, which is a source of input for the program (sends the information as data is being retreived out of the program (writeable stream))

// stdin: a standard output stream, which is a source of output for the program (listens for the user input (readable stream))

// stderr: a standard error stream used for error messages and diagnositcs issued by the program

// env: hosts all the environment variables set at the moment the process was started


process {
    version: 'v16.15.0',
    versions: {
      node: '16.15.0',
      v8: '9.4.146.24-node.20',
      uv: '1.43.0',
      zlib: '1.2.11',
      brotli: '1.0.9',
      ares: '1.18.1',
      modules: '93',
      nghttp2: '1.47.0',
      napi: '8',
      llhttp: '6.0.4',
      openssl: '1.1.1n+quic',
      cldr: '40.0',
      icu: '70.1',
      tz: '2021a3',
      unicode: '14.0',
      ngtcp2: '0.1.0-DEV',
      nghttp3: '0.1.0-DEV'
    },
    arch: 'arm64',
    platform: 'darwin',
    release: {
      name: 'node',
      lts: 'Gallium',
      sourceUrl: 'https://nodejs.org/download/release/v16.15.0/node-v16.15.0.tar.gz',
      headersUrl: 'https://nodejs.org/download/release/v16.15.0/node-v16.15.0-headers.tar.gz'
    },
    _rawDebug: [Function: _rawDebug],
    moduleLoadList: [
      'Internal Binding native_module',
      'Internal Binding errors',
      'NativeModule internal/errors',
      'Internal Binding config',
      'Internal Binding timers',
      'Internal Binding async_wrap',
      'Internal Binding constants',
      'Internal Binding util',
      'Internal Binding types',
      'NativeModule internal/util',
      'NativeModule internal/util/types',
      'NativeModule internal/validators',
      'NativeModule internal/promise_hooks',
      'Internal Binding task_queue',
      'Internal Binding symbols',
      'NativeModule internal/async_hooks',
      'NativeModule internal/linkedlist',
      'NativeModule internal/priority_queue',
      'NativeModule internal/assert',
      'Internal Binding icu',
      'NativeModule internal/util/inspect',
      'NativeModule internal/util/debuglog',
      'NativeModule internal/timers',
      'NativeModule events',
      'Internal Binding buffer',
      'Internal Binding string_decoder',
      'NativeModule internal/buffer',
      'Internal Binding blob',
      'NativeModule internal/encoding',
      'Internal Binding messaging',
      'NativeModule internal/worker/js_transferable',
      'NativeModule internal/constants',
      'NativeModule internal/blob',
      'NativeModule buffer',
      'NativeModule internal/modules/esm/handle_process_exit',
      'Internal Binding process_methods',
      'NativeModule internal/process/per_thread',
      'Internal Binding credentials',
      'NativeModule internal/process/promises',
      'NativeModule internal/fixed_queue',
      'NativeModule async_hooks',
      'NativeModule internal/process/task_queues',
      'Internal Binding trace_events',
      'NativeModule internal/console/constructor',
      'NativeModule internal/console/global',
      'NativeModule internal/util/inspector',
      'Internal Binding inspector',
      'NativeModule internal/querystring',
      'NativeModule path',
      'NativeModule querystring',
      'Internal Binding url',
      'NativeModule internal/url',
      'NativeModule util',
      'Internal Binding performance',
      'NativeModule internal/perf/utils',
      'NativeModule internal/event_target',
      'NativeModule timers',
      'NativeModule internal/abort_controller',
      'Internal Binding worker',
      'NativeModule internal/streams/end-of-stream',
      'NativeModule internal/streams/operators',
      'NativeModule internal/streams/destroy',
      'NativeModule internal/streams/legacy',
      'NativeModule internal/streams/add-abort-signal',
      'NativeModule internal/streams/buffer_list',
      'NativeModule internal/streams/state',
      'NativeModule string_decoder',
      'NativeModule internal/streams/from',
      'NativeModule internal/streams/readable',
      'NativeModule internal/streams/writable',
      'NativeModule internal/streams/duplex',
      'NativeModule internal/streams/utils',
      'NativeModule internal/streams/pipeline',
      'NativeModule internal/streams/compose',
      'NativeModule stream/promises',
      'NativeModule internal/streams/transform',
      'NativeModule internal/streams/passthrough',
      'NativeModule stream',
      'NativeModule internal/worker/io',
      'NativeModule internal/perf/performance_entry',
      'NativeModule internal/perf/observe',
      'NativeModule internal/perf/nodetiming',
      'NativeModule internal/perf/usertiming',
      'NativeModule internal/perf/event_loop_utilization',
      'NativeModule internal/histogram',
      'NativeModule internal/perf/timerify',
      'NativeModule internal/perf/performance',
      'NativeModule internal/perf/event_loop_delay',
      'NativeModule perf_hooks',
      'NativeModule internal/process/execution',
      'NativeModule internal/process/warning',
      'Internal Binding fs',
      'NativeModule internal/fs/utils',
      'Internal Binding fs_dir',
      'NativeModule internal/fs/dir',
      'Internal Binding fs_event_wrap',
      'Internal Binding uv',
      'NativeModule internal/fs/watchers',
      'NativeModule internal/fs/read_file_context',
      'NativeModule fs',
      ... 73 more items
    ],
    binding: [Function: binding],
    _linkedBinding: [Function: _linkedBinding],
    _events: [Object: null prototype] {
      newListener: [ [Function: startListeningIfSignal], [Function (anonymous)] ],
      removeListener: [ [Function: stopListeningIfSignal], [Function (anonymous)] ],
      warning: [Function: onWarning],
      SIGWINCH: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    domain: [Getter/Setter],
    _exiting: false,
    config: [Getter/Setter],
    dlopen: [Function: dlopen],
    uptime: [Function: uptime],
    _getActiveRequests: [Function: _getActiveRequests],
    _getActiveHandles: [Function: _getActiveHandles],
    getActiveResourcesInfo: [Function (anonymous)],
    reallyExit: [Function: reallyExit],
    _kill: [Function: _kill],
    cpuUsage: [Function: cpuUsage],
    resourceUsage: [Function: resourceUsage],
    memoryUsage: [Function: memoryUsage] { rss: [Function: rss] },
    kill: [Function: kill],
    exit: [Function: exit],
    hrtime: [Function: hrtime] { bigint: [Function: hrtimeBigInt] },
    openStdin: [Function (anonymous)],
    getuid: [Function: getuid],
    geteuid: [Function: geteuid],
    getgid: [Function: getgid],
    getegid: [Function: getegid],
    getgroups: [Function: getgroups],
    allowedNodeEnvironmentFlags: [Getter/Setter],
    assert: [Function: deprecated],
    features: {
      inspector: true,
      debug: false,
      uv: true,
      ipv6: true,
      tls_alpn: true,
      tls_sni: true,
      tls_ocsp: true,
      tls: true,
      cached_builtins: [Getter]
    },
    _fatalException: [Function (anonymous)],
    setUncaughtExceptionCaptureCallback: [Function (anonymous)],
    hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback],
    emitWarning: [Function: emitWarning],
    nextTick: [Function: nextTick],
    _tickCallback: [Function: runNextTicks],
    _debugProcess: [Function: _debugProcess],
    _debugEnd: [Function: _debugEnd],
    _startProfilerIdleNotifier: [Function (anonymous)],
    _stopProfilerIdleNotifier: [Function (anonymous)],
    stdout: [Getter],
    stdin: [Getter],
    stderr: [Getter],
    abort: [Function: abort],
    umask: [Function: wrappedUmask],
    chdir: [Function (anonymous)],
    cwd: [Function: wrappedCwd],
    initgroups: [Function: initgroups],
    setgroups: [Function: setgroups],
    setegid: [Function (anonymous)],
    seteuid: [Function (anonymous)],
    setgid: [Function (anonymous)],
    setuid: [Function (anonymous)],
    env: {
      USER: 'yungshotta',
      __CFBundleIdentifier: 'com.microsoft.VSCode',
      COMMAND_MODE: 'unix2003',
      LOGNAME: 'yungshotta',
      PATH: '/Users/yungshotta/.yarn/bin:/Users/yungshotta/.config/yarn/global/node_modules/.bin:/Users/yungshotta/opt/anaconda3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Apple/usr/bin:/Users/yungshotta/.yarn/bin:/Users/yungshotta/.config/yarn/global/node_modules/.bin:/Users/yungshotta/opt/anaconda3/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/local/bin:/opt/local/sbin:/Users/yungshotta/.fig/bin:/Users/yungshotta/.local/bin',
      SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.LuLp1lM6Ad/Listeners',
      SHELL: '/bin/zsh',
      HOME: '/Users/yungshotta',
      __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0',
      TMPDIR: '/var/folders/72/1vcn77h95nd174cfr6ms0q400000gn/T/',
      XPC_SERVICE_NAME: '0',
      XPC_FLAGS: '0x0',
      ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
      SHLVL: '1',
      PWD: '/Users/yungshotta/Devmountain Spec/week 12/web-node-drills-1/app-2',
      OLDPWD: '/Users/yungshotta/Devmountain Spec/week 12/web-node-drills-1',
      HOMEBREW_PREFIX: '/opt/homebrew',
      HOMEBREW_CELLAR: '/opt/homebrew/Cellar',
      HOMEBREW_REPOSITORY: '/opt/homebrew',
      MANPATH: '/opt/homebrew/share/man:/usr/share/man:/usr/local/share/man:/opt/homebrew/share/man:',
      INFOPATH: '/opt/homebrew/share/info:/opt/homebrew/share/info:',
      TTY: '/dev/ttys001',
      FIG_PID: '27029',
      TERM_PROGRAM: 'vscode',
      TERM_PROGRAM_VERSION: '1.67.2',
      LANG: 'en_US.UTF-8',
      COLORTERM: 'truecolor',
      VSCODE_GIT_IPC_HANDLE: '/var/folders/72/1vcn77h95nd174cfr6ms0q400000gn/T/vscode-git-bc54d2d328.sock',
      VSCODE_GIT_ASKPASS_NODE: '/Applications/Visual Studio Code.app/Contents/MacOS/Electron',
      VSCODE_GIT_ASKPASS_EXTRA_ARGS: '--ms-enable-electron-run-as-node',
      VSCODE_GIT_ASKPASS_MAIN: '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js',
      GIT_ASKPASS: '/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh',
      TERM: 'xterm-256color',
      TERM_SESSION_ID: '3EEB2EB6-BEA9-4063-99B2-55D20C1875DC',
      FIG_INTEGRATION_VERSION: '8',
      FIG_TERM: '1',
      FIG_TERM_VERSION: '4.4.0',
      _: '/usr/local/bin/node'
    },
    title: 'node',
    argv: [ '/usr/local/bin/node' ],
    execArgv: [],
    pid: 27090,
    ppid: 27029,
    execPath: '/usr/local/bin/node',
    debugPort: 9229,
    argv0: 'node',
    _preload_modules: [],
    report: [Getter],
    setSourceMapsEnabled: [Function: setSourceMapsEnabled],
    [Symbol(kCapture)]: false
  }